spring:
  config:
    import: application-local.yml
    
  profiles:
    active: local
    
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASS}
mybatis:
  mapper-locations: classpath:mapper/**/*.xml
  type-aliases-package: simon.com